<?php
	$keytermsarray = array(
	    array("term_id"=>"1", "term"=>"Activities"),
	    array("term_id"=>"2", "term"=>"Armour"),
	    array("term_id"=>"3", "term"=>"Barrowlands"),
	    array("term_id"=>"4", "term"=>"Bees"),
	    array("term_id"=>"5", "term"=>"Billy Connolly"),
	    array("term_id"=>"6", "term"=>"Buddhism"),
	    array("term_id"=>"7", "term"=>"Bus"),
	    array("term_id"=>"8", "term"=>"Cafe"),
	    array("term_id"=>"9", "term"=>"Car"),
	    array("term_id"=>"10", "term"=>"Christianity"),
	    array("term_id"=>"11", "term"=>"City Centre"),
	    array("term_id"=>"12", "term"=>"Coffee Shop"),
	    array("term_id"=>"13", "term"=>"Dali"),
	    array("term_id"=>"14", "term"=>"Degas"),
	    array("term_id"=>"15", "term"=>"East End"),
	    array("term_id"=>"16", "term"=>"Exhibitions"),
	    array("term_id"=>"17", "term"=>"Garden"),
	    array("term_id"=>"18", "term"=>"Hall Of Fame"),
	    array("term_id"=>"19", "term"=>"Hampden"),
	    array("term_id"=>"20", "term"=>"Hinduism"),
	    array("term_id"=>"21", "term"=>"House"),
	    array("term_id"=>"22", "term"=>"Installations"),
	    array("term_id"=>"23", "term"=>"Interactive"),
	    array("term_id"=>"24", "term"=>"Islam"),
	    array("term_id"=>"25", "term"=>"Judaism"),
	    array("term_id"=>"26", "term"=>"Mackintosh"),
	    array("term_id"=>"27", "term"=>"Medieval"),
	    array("term_id"=>"28", "term"=>"Modern Art"),
	    array("term_id"=>"29", "term"=>"Monet"),
	    array("term_id"=>"30", "term"=>"Organ"),
	    array("term_id"=>"31", "term"=>"Painting"),
	    array("term_id"=>"32", "term"=>"Parking"),
	    array("term_id"=>"33", "term"=>"Picasso"),
	    array("term_id"=>"34", "term"=>"Plane"),
	    array("term_id"=>"35", "term"=>"Pollok Park"),
	    array("term_id"=>"36", "term"=>"Rembrandt"),
	    array("term_id"=>"37", "term"=>"Renoir"),
	    array("term_id"=>"38", "term"=>"River Clyde"),
	    array("term_id"=>"39", "term"=>"River Kelvin"),
	    array("term_id"=>"40", "term"=>"Sculpture"),
	    array("term_id"=>"41", "term"=>"Shop"),
	    array("term_id"=>"42", "term"=>"South Side"),
	    array("term_id"=>"43", "term"=>"Spitfire"),
	    array("term_id"=>"44", "term"=>"Streets"),
	    array("term_id"=>"45", "term"=>"Tall Ship"),
	    array("term_id"=>"46", "term"=>"Taxidermy"),
	    array("term_id"=>"47", "term"=>"Train"),
	    array("term_id"=>"48", "term"=>"Tram"),
	    array("term_id"=>"49", "term"=>"Van Gogh"),
	    array("term_id"=>"50", "term"=>"West End")
	);
	echo '{"keyterms":';
	echo json_encode($keytermsarray) . '}';
?>	
