<?php
	$museumsarray = array(
		array("museum_id" => "1", "museum_name" => "Kelvingrove Art Gallery and Museum", "museum_description" => "Glasgow's main art gallery and museum situated in the west end of the city.", "museum_type" => "Art Gallery",
				"address" => "Argyle Street", "postcode" => "G3 8AG", "lat" => "55.8684124", "long" => "-4.29054489999998", "website" => "http://www.glasgowlife.org.uk/museums/kelvingrove/Pages/default.aspx",
				"distance_citycentre" => array("driving_miles"=>"2.2", "driving_minutes"=>"12", "walking_miles"=>"1.7", "walking_minutes"=>"34"),
				"opening_hours" => array("Monday"=>"10am-5pm","Tuesday"=>"10am-5pm","Wednesday"=>"10am-5pm","Thursday"=>"10am-5pm","Friday"=>"11am-5pm","Saturday"=>"10am-5pm","Sunday"=>"11am-5pm"),
				"closed_days" => array("January 1st", "January 2nd", "December 24th", "December 25th", "December 26th", "December 31st"),
				"images" => array(
					array("image_id" => "34", "description" => "Front View Of Kelvingrove", "url" => "Kelvingrove_Front_View_1 (Medium).jpg"),
					array("image_id" => "35", "description" => "Front View Of Kelvingrove", "url" => "Kelvingrove_Front_View_2 (Medium).jpg"),
					array("image_id" => "36", "description" => "Front View Of Kelvingrove", "url" => "Kelvingrove_Front_View_3 (Medium).jpg"),
					array("image_id" => "37", "description" => "Front View Of Kelvingrove", "url" => "Kelvingrove_Front_View_4 (Medium).jpg"),
					array("image_id" => "38", "description" => "Rear View Of Kelvingrove", "url" => "Kelvingrove_Rear_View_1 (Medium).jpg"),
					array("image_id" => "39", "description" => "Rear View Of Kelvingrove", "url" => "Kelvingrove_Rear_View_2 (Medium).jpg"),
					array("image_id" => "40", "description" => "Organ in Kelvingrove Art Gallery", "url" => "Organ_Kelvingrove (Medium).jpg"),
					array("image_id" => "41", "description" => "Heads Exhibit at Kelvingrove", "url" => "Heads_Kelvingrove (Medium).jpg"),
					array("image_id" => "42", "description" => "Exhibits at Kelvingrove", "url" => "Plane_Elephant_Giraffe (Medium).jpg")
				),
				"keyterms" => array(1,2,4,8,12,13,16,23,26,27,29,30,31,32,33,34,36,39,40,41,43,46,49,50)
		),
		array("museum_id" => "2", "museum_name" => "Gallery of Modern Art", "museum_description" => "The main gallery of contemporary art in Glasgow focusing on temporary exhibitions and workshops.", "museum_type" => "Art Gallery",
				"address" => "Royal Exchange Square", "postcode" => "G1 3AH", "lat" => "55.8598042", "long" => "-4.2524844", "website" => "http://www.glasgowlife.org.uk/museums/GoMA/Pages/default.aspx",
				"distance_citycentre" => array("driving_miles"=>"1.2", "driving_minutes"=>"14", "walking_miles"=>"0.6", "walking_minutes"=>"11"),
				"opening_hours" => array("Monday"=>"10am-5pm","Tuesday"=>"10am-5pm","Wednesday"=>"10am-5pm","Thursday"=>"10am-8pm","Friday"=>"11am-5pm","Saturday"=>"11am-5pm","Sunday"=>"11am-5pm"),
				"closed_days" => array("January 1st", "January 2nd", "December 24th", "December 25th", "December 26th", "December 31st"),
				"images" => array(
					array("image_id" => "19", "description" => "A rear view of the GOMA", "url" => "GOMA_Rear (Medium).jpg"),
					array("image_id" => "20", "description" => "Side View Of The GOMA", "url" => "GOMA_Sideview_1 (Medium).jpg"),
					array("image_id" => "21", "description" => "Side View Of The GOMA", "url" => "GOMA_Sideview_2 (Medium).jpg"),
					array("image_id" => "22", "description" => "Front View Of The GOMA", "url" => "GOMA_Front_View_1 (Medium).jpg"),
					array("image_id" => "23", "description" => "Front View Of The GOMA", "url" => "GOMA_Front_View_2 (Medium).jpg"),
					array("image_id" => "24", "description" => "Front View Of The GOMA", "url" => "GOMA_Front_View_3 (Medium).jpg"),
					array("image_id" => "25", "description" => "Internal View Of The GOMA", "url" => "GOMA_Internal_View (Medium).jpg"),
					array("image_id" => "26", "description" => "Main Exhibition Space", "url" => "GOMA_Main_Exhibition_Space (Medium).jpg"),
					array("image_id" => "27", "description" => "Duke Of Wellington equestrain statue outside GOMA", "url" => "Duke_Of_Wellington_GOMA (Medium).jpg")
				),
				"keyterms" => array(1,8,11,16,22,23,28,31,40,41)
		),
		array("museum_id" => "3", "museum_name" => "St Mungo Museum of Religious Life & Art", "museum_description" => "Located in Cathedral Square with exhibits relating to all the world's major religions.", "museum_type" => "Religion",
				"address" => "2 Castle Street", "postcode" => "G4 0RH", "lat" => "55.8624613", "long" => "-4.236401300000011", "website" => "http://www.glasgowlife.org.uk/museums/st-mungos/Pages/default.aspx",
				"distance_citycentre" => array("driving_miles"=>"0.8", "driving_minutes"=>"6", "walking_miles"=>"0.7", "walking_minutes"=>"14"),
				"opening_hours" => array("Monday"=>"Closed","Tuesday"=>"10am-5pm","Wednesday"=>"10am-5pm","Thursday"=>"10am-5pm","Friday"=>"11am-5pm","Saturday"=>"10am-5pm","Sunday"=>"11am-5pm"),
				"closed_days" => array("January 1st", "January 2nd", "December 24th", "December 25th", "December 26th", "December 31st"),
				"images" => array(
					array("image_id" => "28", "description" => "Rear View Of the St Mungo Museum", "url" => "Rear_View_St_Mungos_1 (Medium).jpg"),
					array("image_id" => "29", "description" => "Rear View Of the St Mungo Museum", "url" => "Rear_View_St_Mungos_2 (Medium).jpg"),
					array("image_id" => "30", "description" => "St Mungo Museum Sign", "url" => "St_Mungo_Sign (Medium).jpg"),
					array("image_id" => "31", "description" => "Garden of the St Mungo Museum", "url" => "Garden_St_Mungo_1 (Medium).jpg"),
					array("image_id" => "32", "description" => "Garden of the St Mungo Museum", "url" => "Garden_St_Mungo_2 (Medium).jpg"),
					array("image_id" => "33", "description" => "Side View of the St Mungo Museum", "url" => "Side_View_St_Mungo_1 (Medium).jpg"),
					array("image_id" => "34", "description" => "Front View of the St Mungo Museum", "url" => "Front_View_St_Mungo (Medium).jpg"),
					array("image_id" => "35", "description" => "David Livingstone", "url" => "David_Livingstone (Medium).jpg")
				),
				"keyterms" => array(6,8,10,11,16,17,20,24,25,27,31,40,41)
		),
		array("museum_id" => "4", "museum_name" => "Riverside Museum", "museum_description" => "Glasgow's Museum of Transport with exhibits relating to all modes of transport.", "museum_type" => "Transport",
				"address" => "100 Pointhouse Place", "postcode" => "G3 8RS", "lat" => "55.8651338", "long" => "-4.3063185", "website" => "http://www.glasgowlife.org.uk/museums/riverside/Pages/default.aspx",
				"distance_citycentre" => array("driving_miles"=>"3.3", "driving_minutes"=>"9", "walking_miles"=>"2.6", "walking_minutes"=>"51"),
				"opening_hours" => array("Monday"=>"10am-5pm","Tuesday"=>"10am-5pm","Wednesday"=>"10am-5pm","Thursday"=>"10am-5pm","Friday"=>"11am-5pm","Saturday"=>"10am-5pm","Sunday"=>"11am-5pm"),
				"closed_days" => array("January 1st", "January 2nd", "December 24th", "December 25th", "December 26th", "December 31st"),
				"images" => array(
					array("image_id" => "36", "description" => "Glasgow Tram at the Riverside", "url" => "Riverside_Tram_1 (Medium).jpg"),
					array("image_id" => "37", "description" => "Glasgow Tram at the Riverside", "url" => "Riverside_Tram_2 (Medium).jpg"),
					array("image_id" => "38", "description" => "Glasgow Tram at the Riverside", "url" => "Riverside_Tram_3 (Medium).jpg"),
					array("image_id" => "39", "description" => "Cars at the Riverside", "url" => "Cars_Riverside_1 (Medium).jpg"),
					array("image_id" => "40", "description" => "Cars at the Riverside", "url" => "Cars_Riverside_2 (Medium).jpg"),
					array("image_id" => "41", "description" => "Cars at the Riverside", "url" => "Cars_Riverside_3 (Medium).jpg"),
					array("image_id" => "42", "description" => "Cars at the Riverside", "url" => "Cars_Riverside_4 (Medium).jpg"),
					array("image_id" => "43", "description" => "A traditional underground carriage at the Riverside", "url" => "Underground_Train_Riverside (Medium).jpg"),
					array("image_id" => "44", "description" => "A Horse Drawn Tram  at the Riverside", "url" => "Horse_Drawn_Tram_Riverside (Medium).jpg"),
					array("image_id" => "45", "description" => "Various Railway Engines at the Riverside", "url" => "Engines_Riverside (Medium).jpg"),
					array("image_id" => "46", "description" => "Front View Of the Riverside Museum", "url" => "Front_View_Riverside_1 (Medium).jpg"),
					array("image_id" => "47", "description" => "Front View Of the Riverside Museum", "url" => "Front_View_Riverside_2 (Medium).jpg"),
					array("image_id" => "48", "description" => "Tall Ship at the Riverside", "url" => "Tall_Ship_Riverside_1 (Medium).jpg"),
					array("image_id" => "49", "description" => "Tall Ship at the Riverside", "url" => "Tall_Ship_Riverside_2 (Medium).jpg"),
					array("image_id" => "50", "description" => "Tall Ship at the Riverside", "url" => "Tall_Ship_Riverside_3 (Medium).jpg"),
					array("image_id" => "51", "description" => "Tall Ship at the Riverside", "url" => "Tall_Ship_Riverside_4 (Medium).jpg"),
					array("image_id" => "52", "description" => "Rear View Of the Riverside Museum", "url" => "Rear_View_Riverside (Medium).jpg"),
					array("image_id" => "53", "description" => "Bikes at the Riverside", "url" => "Bikes_Riverside (Medium).jpg"),
					array("image_id" => "54", "description" => "Fire Engine at the Riverside", "url" => "Fire_Engine_Riverside (Medium).jpg"),
					array("image_id" => "55", "description" => "Glasgow Bus at the Riverside", "url" => "Bus_Riverside (Medium).jpg"),
					array("image_id" => "56", "description" => "Bike with sidecar at the Riverside", "url" => "Sidecar_Riverside (Medium).jpg")
				),
				"keyterms" => array(1,7,8,9,12,23,32,34,38,41,44,45,47,48)
		),
		array("museum_id" => "5", "museum_name" => "Scottish Football Museum", "museum_description" => "The Scottish Football League's National Museum of Football based at the National Stadium at Hampden Park.", "museum_type" => "Football",
				"address" => "Hampden Park", "postcode" => "G42 9BA", "lat" => "55.8252342", "long" => "-4.2531995", "website" => "http://www.scottishfootballmuseum.org.uk/",
				"distance_citycentre" => array("driving_miles"=>"4.9", "driving_minutes"=>"19", "walking_miles"=>"3.0", "walking_minutes"=>"62"),
				"opening_hours" => array("Monday"=>"10am-5pm","Tuesday"=>"10am-5pm","Wednesday"=>"10am-5pm","Thursday"=>"10am-5pm","Friday"=>"10am-5pm","Saturday"=>"10am-5pm","Sunday"=>"11am-5pm"),
				"closed_days" => array("January 1st", "January 2nd", "December 24th", "December 25th", "December 26th", "December 31st", "Event Days as advertised"),
				"images" => array(
					array("image_id" => "57", "description" => "Model of Hampden Stadium", "url" => "Hampden_Model (Medium).jpg"),
					array("image_id" => "58", "description" => "Bill Shankly Photo at Hampden", "url" => "Hampden_Bill_Shankly (Medium).jpg"),
					array("image_id" => "59", "description" => "Interior Entrance to the Scottish Football Museum at Hampden", "url" => "Scottish_Football_Museum_Entrance (Medium).jpg"),
					array("image_id" => "60", "description" => "Watching The Game", "url" => "Watching_The_Game (Medium).jpg"),
					array("image_id" => "61", "description" => "Trophy Exhibition", "url" => "Trophies (Medium).jpg"),
					array("image_id" => "62", "description" => "Welcome To Hampden Park", "url" => "Welcome_To_Hampden_Park (Medium).jpg")
				),
				"keyterms" => array(8,16,18,19,32,41)
		),
		array("museum_id" => "6", "museum_name" => "People's Palace", "museum_description" => "Situated in the east end of the city reflecting the culture and history of local residents, it incorparates a glasshouse known as the Winter Gardens.", "museum_type" => "Culture",
				"address" => "Glasgow Green ", "postcode" => "G40 1AT", "lat" => "55.8512074", "long" => "-4.2369848", "website" => "http://www.glasgowlife.org.uk/museums/peoples-palace/Pages/default.aspx",
				"distance_citycentre" => array("driving_miles"=>"1.5", "driving_minutes"=>"12", "walking_miles"=>"1.4", "walking_minutes"=>"28"),
				"opening_hours" => array("Monday"=>"Closed","Tuesday"=>"10am-5pm","Wednesday"=>"10am-5pm","Thursday"=>"10am-5pm","Friday"=>"11am-5pm","Saturday"=>"10am-5pm","Sunday"=>"11am-5pm"),
				"closed_days" => array("January 1st", "January 2nd", "December 24th", "December 25th", "December 26th", "December 31st"),
				"images" => array(
					array("image_id" => "63", "description" => "Side View Of The People's Palace", "url" => "Peoples_Palace_Side_View_1 (Medium).jpg"),
					array("image_id" => "64", "description" => "Side View Of The People's Palace", "url" => "Peoples_Palace_Side_View_2 (Medium).jpg"),
					array("image_id" => "65", "description" => "Exterior View Of The Winter Gardens", "url" => "Winter_Gardens_Exterior_View_1 (Medium).jpg"),
					array("image_id" => "66", "description" => "Exterior View Of The Winter Gardens", "url" => "Winter_Gardens_Exterior_View_2 (Medium).jpg"),
					array("image_id" => "67", "description" => "Fountain outside the People's Palace", "url" => "Peoples_Palace_Fountain_1 (Medium).jpg"),
					array("image_id" => "68", "description" => "Fountain outside the People's Palace", "url" => "Peoples_Palace_Fountain_2 (Medium).jpg"),
					array("image_id" => "69", "description" => "Stairway at entrance of the People's Palace", "url" => "Stairway_Peoples_Palace (Medium).jpg"),
					array("image_id" => "70", "description" => "Interior View Of The Winter Gardens", "url" => "Interior_View_Winter_Gardens_1 (Medium).jpg"),
					array("image_id" => "71", "description" => "Interior View Of The Winter Gardens", "url" => "Interior_View_Winter_Gardens_2 (Medium).jpg"),
					array("image_id" => "72", "description" => "Interior View Of The Winter Gardens", "url" => "Interior_View_Winter_Gardens_3 (Medium).jpg"),
					array("image_id" => "73", "description" => "Interior View Of The Winter Gardens", "url" => "Interior_View_Winter_Gardens_4 (Medium).jpg"),
					array("image_id" => "74", "description" => "Billy Connolly's Banana Boots", "url" => "Big_Banana_Boots (Medium).jpg"),
					array("image_id" => "75", "description" => "Internal Staircase at the People's Palace", "url" => "Internal_Staircase_Peoples_Palace (Medium).jpg"),
					array("image_id" => "76", "description" => "Replica of the Barrowlands Sign at the People's Palace", "url" => "Barrowland_Sign_Peoples_Palace (Medium).jpg"),
					array("image_id" => "77", "description" => "Spanish Civil War Banner at the People's Palace", "url" => "Spanish_Civil_War_Peoples_Palace (Medium).jpg"),
					array("image_id" => "78", "description" => "Caricatures Exhibit at the People's Palace", "url" => "Caricatures_Peoples_Palace (Medium).jpg"),
					array("image_id" => "79", "description" => "Traditional Dairy at the People's Palace", "url" => "Buttercup_Dairy_Peoples_Palace (Medium).jpg"),
					array("image_id" => "80", "description" => "Front View Of the People's Palace", "url" => "Front_View_Peoples_Palace (Medium).jpg")
				),
				"keyterms" => array(1,3,5,11,15,31,38,40,41)
		),
		array("museum_id" => "7", "museum_name" => "Burrell Collection", "museum_description" => "Art collection acquired by Sir William Burrell and donated to the city, situated in Pollok Country Park on the south side of the city.", "museum_type" => "Art Gallery",
				"address" => "2060 Pollokshaws Road", "postcode" => "G43 1AT", "lat" => "55.8232535", "long" => "-4.3033438", "website" => "http://www.glasgowlife.org.uk/museums/burrell-collection/Pages/default.aspx",
				"distance_citycentre" => array("driving_miles"=>"5.7", "driving_minutes"=>"18", "walking_miles"=>"3.9", "walking_minutes"=>"79"),
				"opening_hours" => array("Monday"=>"Closed","Tuesday"=>"Closed","Wednesday"=>"Closed","Thursday"=>"Closed","Friday"=>"Closed","Saturday"=>"Closed","Sunday"=>"Closed"),
				"closed_days" => array("Closed until 2020 for refurbishment"),
				"images" => array(
					array("image_id" => "81", "description" => "Side View Of The Burrell Collection", "url" => "Burrell_SideView_1 (Medium).jpg"),
					array("image_id" => "82", "description" => "Side View Of The Burrell Collection", "url" => "Burrell_SideView_2 (Medium).jpg"),
					array("image_id" => "83", "description" => "Side View Of The Burrell Collection", "url" => "Burrell_SideView_3 (Medium).jpg"),
					array("image_id" => "84", "description" => "Side View Of The Burrell Collection", "url" => "Burrell_SideView_4 (Medium).jpg"),
					array("image_id" => "85", "description" => "Side View Of The Burrell Collection", "url" => "Burrell_SideView_5 (Medium).jpg"),
					array("image_id" => "86", "description" => "Entrance to the Burrell Collection", "url" => "Burrell_Entrance (Medium).jpg"),
					array("image_id" => "87", "description" => "Burrell Collection Sign", "url" => "Burrell_Collection (Medium).jpg"),
					array("image_id" => "88", "description" => "An interior walkway with stained glass exhibits to the right", "url" => "Burrell_Walkway (Medium).jpg"),
					array("image_id" => "89", "description" => "Interior Arch", "url" => "Burrell_Arch_1 (Medium).jpg"),
					array("image_id" => "90", "description" => "Interior Arch", "url" => "Burrell_Arch_2 (Medium).jpg"),
					array("image_id" => "91", "description" => "Interior Arch", "url" => "Burrell_Arch_3 (Medium).jpg"),
					array("image_id" => "92", "description" => "Interior courtyard with trees", "url" => "Burrell_Courtyard (Medium).jpg"),
					array("image_id" => "93", "description" => "An exhibit room", "url" => "Burrell_Room (Medium).jpg"),
					array("image_id" => "94", "description" => "Corridor with exhibit rooms to left and windows to right", "url" => "Burrell_Corridor (Medium).jpg"),
					array("image_id" => "95", "description" => "A close up of some of the stained glass exhibits", "url" => "Burrell_Stained_Glass (Medium).jpg"),
					array("image_id" => "96", "description" => "View from a gallery out to the woods", "url" => "Burrell_Inside_Out (Medium).jpg"),
					array("image_id" => "97", "description" => "Scupltures in glass cases", "url" => "Burrell_Sculpture_1 (Medium).jpg"),
					array("image_id" => "98", "description" => "Scupltures in glass cases", "url" => "Burrell_Sculpture_2 (Medium).jpg")
				),
				"keyterms" => array(1,2,8,12,14,23,27,31,32,35,40,41,42)
		),
		array("museum_id" => "8", "museum_name" => "Provand's Lordship", "museum_description" => "A medieval-period house located in the city centre which is the oldest remining house in Glasgow; built as part of St Nicholas's Hospital and sited opposite the Royal Infirmary and Cathedral Square.", "museum_type" => "History",
				"address" => "3 Castle Street", "postcode" => "G4 0RH", "lat" => "55.864527", "long" => "-4.236292", "website" => "http://www.glasgowlife.org.uk/museums/provands-lordship/Pages/default.aspx",
				"distance_citycentre" => array("driving_miles"=>"0.8", "driving_minutes"=>"7", "walking_miles"=>"0.7", "walking_minutes"=>"15"),
				"opening_hours" => array("Monday"=>"Closed","Tuesday"=>"10am-5pm","Wednesday"=>"10am-5pm","Thursday"=>"10am-5pm","Friday"=>"11am-5pm","Saturday"=>"10am-5pm","Sunday"=>"11am-5pm"),
				"closed_days" => array("January 1st", "January 2nd", "December 24th", "December 25th", "December 26th", "December 31st"),
				"images" => array(
					array("image_id" => "81", "description" => "Garden at the Provand's Lordship", "url" => "Provands_Lordship_Garden_1 (Medium).jpg"),
					array("image_id" => "81", "description" => "Garden at the Provand's Lordship", "url" => "Provands_Lordship_Garden_2 (Medium).jpg"),
					array("image_id" => "81", "description" => "Garden at the Provand's Lordship", "url" => "Provands_Lordship_Garden_3 (Medium).jpg"),
					array("image_id" => "81", "description" => "Garden at the Provand's Lordship", "url" => "Provands_Lordship_Garden_4 (Medium).jpg"),
					array("image_id" => "82", "description" => "Gargoyle at the Provand's Lordship", "url" => "Gargoyle_Provands_Lordship (Medium).jpg"),
					array("image_id" => "83", "description" => "Back Door at the Provand's Lordship", "url" => "Back_Door_Provands_Lordship (Medium).jpg"),
					array("image_id" => "84", "description" => "Provand's Lordship Sign", "url" => "Provands_Lordship_Sign (Medium).jpg"),
					array("image_id" => "97", "description" => "Front View Of the Provand's Lordship", "url" => "Front_View_Provands_Lordship_1 (Medium).jpg"),
					array("image_id" => "97", "description" => "Front View Of the Provand's Lordship", "url" => "Front_View_Provands_Lordship_2 (Medium).jpg"),
					array("image_id" => "97", "description" => "Front View Of the Provand's Lordship", "url" => "Front_View_Provands_Lordship_3 (Medium).jpg"),
					array("image_id" => "97", "description" => "Front View Of the Provand's Lordship", "url" => "Front_View_Provands_Lordship_4 (Medium).jpg"),
					array("image_id" => "98", "description" => "St. Nicholas Garden at the Provand's Lordship", "url" => "St_Nicholas_Garden_Provands_Lordship (Medium).jpg")
				),
				"keyterms" => array(11,17,21,27,32)
		)
	);
	echo '{"museums":';
	echo json_encode($museumsarray) . '}';
?>
